language: python
python:
  - 3.6

install:
  - python setup.py install

script:
  - pytest -v

notifications:
  email:
    recipients:
      - manuel.peuster@upb.de
    on_success: change # default: change
    on_failure: always # default: always
