language: python
python:
  - 3.5

install:
  - python setup.py install

script:
  - pytest -v

notifications:
  email:
    recipients:
      - heidineu@mail.upb.de
    on_success: change # default: change
    on_failure: always # default: always
