---
name: "Analysis of Different DT Parameters"
author: "Heidi Neuhäuser"
version: 0.1

max_time_t: null
repetitions: 5
result_path: "out/DT_parameter_analysis_nfvsdn.pkl"
result_path_add_timestamp: False

pmodels:
    - name: NFVSDN17ExperimentMeasurements
      n_model_instances: 10
      topologies: ["nx-sc-sq", "sc-sq-nx", "sq-nx-sc", "nx-sc-sq-phys-isolated", "sc-sq-nx-phys-isolated", "sq-nx-sc-phys-isolated"]
      raw_data_path: "analysis/data/peuster_karl_ieeenfvsdn17_3vnf_sfc_profile.pkl"


selector:
    - name: DecisionTreeSelector
      max_samples: {min: 4, max: 36, step: 4}
      initial_samples: 8
      max_depth: 100
      regression: default
      min_samples_split: 4
      weight_size: 0.4
    - name: DecisionTreeSelector
      max_samples: {min: 4, max: 36, step: 4}
      initial_samples: 12
      max_depth: 100
      regression: default
      min_samples_split: 4
      weight_size: 0.4
    - name: DecisionTreeSelector
      max_samples: {min: 4, max: 36, step: 4}
      initial_samples: 8
      max_depth: 100
      regression: default
      min_samples_split: 4
      weight_size: 0.5
    - name: DecisionTreeSelector
      max_samples: {min: 4, max: 36, step: 4}
      initial_samples: 12
      max_depth: 100
      regression: default
      min_samples_split: 4
      weight_size: 0.5
    - name: DecisionTreeSelector
      max_samples: {min: 4, max: 36, step: 4}
      initial_samples: 8
      max_depth: 100
      regression: default
      min_samples_split: 4
      weight_size: 0.6
    - name: DecisionTreeSelector
      max_samples: {min: 4, max: 36, step: 4}
      initial_samples: 12
      max_depth: 100
      regression: default
      min_samples_split: 4
      weight_size: 0.6
    - name: DecisionTreeSelector
      max_samples: {min: 4, max: 36, step: 4}
      initial_samples: 8
      max_depth: 100
      regression: default
      min_samples_split: 4
      weight_size: 0.7
    - name: DecisionTreeSelector
      max_samples: {min: 4, max: 36, step: 4}
      initial_samples: 12
      max_depth: 100
      regression: default
      min_samples_split: 4
      weight_size: 0.7
    - name: DecisionTreeSelector
      max_samples: {min: 4, max: 36, step: 4}
      initial_samples: 4
      max_depth: 100
      regression: default
      min_samples_split: 2
      weight_size: 0.5
    - name: DecisionTreeSelector
      max_samples: {min: 4, max: 36, step: 4}
      initial_samples: 8
      max_depth: 100
      regression: default
      min_samples_split: 2
      weight_size: 0.5
    - name: DecisionTreeSelector
      max_samples: {min: 4, max: 36, step: 4}
      initial_samples: 12
      max_depth: 100
      regression: default
      min_samples_split: 2
      weight_size: 0.5


predictor:
    - name: PolynomialRegressionPredictor
      degree: [3]  # poly. degree (expandable)
    - name: DecisionTreeRegressionPredictor
    - name: SVRPredictorRbfKernel
      epsilon: [0.1]  # epsilon (expandable)
      scale_x: True
    - name: SVRPredictorLinearKernel
      epsilon: [0.1]  # epsilon (expandable)
      scale_x: True
    - name: SVRPredictorPolyKernel
      epsilon: [0.1]  # epsilon (expandable)
      scale_x: True

error_metrics:
    - name: MSE
    - name: RMSD
    - name: NRMSDMean
    - name: NRMSDRange


plot:
    - name: Boxplot
      path: plots
      title: Error
      x: k_samples
      y: error_value
      n_plots:
        # list of columns that distinguish plots
        - selector
        - predictor
        - degree
        - epsilon
        - error
    - name: Lineplot
      path: plots
      title: Selector Error Comparison
      x: k_samples
      y: error_value
      # column that distinguishes lines in plot
      hue: selector_conf
      error_bars: 95  # ="sd" or =95 (for ci)
      n_plots:
        # list of columns that distinguish plots
        - predictor
        - degree
        - epsilon
        - error
    - name: Lineplot
      # needs fixed argument values for predictors!
      path: plots
      title: Predictor Error Comparison
      x: k_samples
      y: error_value
      # column that distinguishes lines in plot
      hue: predictor_conf
      error_bars: 95  # ="sd" or =95 (for ci)
      n_plots:
        # list of columns that distinguish plots
        - selector
        - error
