---
# This is an example configuration for a single experiment.
name: "Cross validation with PANIC results"
author: "Manuel Peuster"
version: 0.1

# time limit for measurement (s) (expandable)
sim_t_max: null
repetitions: 1000
# path to write results as pickled Pandas DF 
result_path: "out/cross_validation_panic_terrasort.pkl"
result_path_add_timestamp: False

pmodel:
    name: PanicTerrasortModel

# PANIC Paper: 135 configs * 0.2 (sampling rate) = 27
# max_samples: {min: 5, max: 27, step: 1}
# 90 = sqrt(8000)
selector:
    - name: UniformRandomSelector
      # max. no. of samples to be selected (expandable)
      max_samples: {min: 2, max: 27, step: 1}
    #- name: UniformGridSelector
    #  # max. no. of samples to be selected (expandable)
    #  max_samples: {min: 2, max: 90, step: 1}
    - name: UniformGridSelectorRandomOffset
      # max. no. of samples to be selected (expandable)
      max_samples: {min: 2, max: 27, step: 1}
    - name: UniformGridSelectorIncrementalOffset
      # max. no. of samples to be selected (expandable)
      max_samples: {min: 5, max: 27, step: 1}
    - name: PanicGreedyAdaptiveSelector
      # max. no. of samples to be selected (expandable)
      max_samples: {min: 2, max: 27, step: 1}
      max_border_points: 8  # PANIC: 2^d (d=parameter space dimension)

predictor:
    - name: PolynomialRegressionPredictor
      # poly. degree (expandable)
      degree: [2, 3, 4]
    - name: SupportVectorRegressionPredictor
      epsilon: [0.01, 0.1, 0.5]  # epsilon (expandable)

error_metrics:
    - name: MSE
    - name: MAE
    - name: R2
    #- name: EVS

plot:
    - name: Boxplot
      disabled: True
      path: plots
      title: Error
      x: k_samples
      y: error_value
      y_lim_min: null
      y_lim_max: null
      n_plots:
        # list of columns that distinguish plots
        - selector
        - predictor
        - degree
        - epsilon
        - error
    - name: Lineplot
      disabled: False
      path: plots
      title: Selector Error Comparison
      x: k_samples
      y: error_value
      y_lim_min: null
      y_lim_max: null
      line_plots:  # column defining lines in plot
        - selector
      n_plots:
        # list of columns that distinguish plots
        - predictor
        - degree
        - epsilon
        - error
    - name: Lineplot
      disabled: True
      # needs fixed argument values for predictors!
      path: plots
      title: Predictor Error Comparison
      x: k_samples
      y: error_value
      y_lim_min: null
      y_lim_max: null
      line_plots:
        - predictor
        - epsilon
        - degree
      n_plots:
        # list of columns that distinguish plots
        - selector
        - error
