---
name: "Cross validation experiment"
author: "Manuel Peuster"
version: 0.1

# time limit for measurement (s) (expandable)
sim_t_max: null
repetitions: 100
# path to write results as pickled Pandas DF 
result_path: "out/crossval.pkl"

pmodel:
    name: CrossValidationModel

selector:
    - name: UniformRandomSelector
      # max. no. of samples to be selected (expandable)
      max_samples: {min: 2, max: 40, step: 2}

predictor:
    name: PolynomialRegressionPredictor
    # poly. degree (expandable)
    degree: {min: 1, max: 6, step: 1}
    
error_metrics:
    - name: MSE
    - name: MAE
    - name: R2
    - name: EVS

plot:
    name: Boxplot
    path: plots
    title: Error
    x: k_samples
    y: error_value
    n_plots: degree
