---
# This is an example configuration for a single experiment that uses the Decision Tree Selector.
name: "DT Example Experiment"
author: "Heidi Neuhäuser"
version: 0.1

max_time_t: null
repetitions: 5
result_path: "out/dt-test-experiment.pkl"
result_path_add_timestamp: False

pmodels:
    - name: ExampleModel

selector:
    - name: DecisionTreeSelector
      max_samples: {min: 2, max: 36, step: 4}
      min_samples_split: 6
      weight_size: 0.6
      split: default
      error_metric: mse

predictor:
    - name: DecisionTreeRegressionPredictor

error_metrics:
    - name: NRMSDRange
