---
# This is an example configuration for a single experiment.
name: "Selection algorithms comp. using NFV-SDN'17 paper model."
author: "Manuel Peuster"
version: 0.1

# time limit for measurement (s) (expandable)
sim_t_max: null
repetitions: 100
# path to write results as pickled Pandas DF 
result_path: "out/selectors-nfvsdn17-model.pkl"

pmodel:
    name: NFVSDN17Model

selector:
    - name: UniformRandomSelector
      # max. no. of samples to be selected (expandable)
      max_samples: {min: 2, max: 40, step: 1}
    - name: UniformGridSelector
      # max. no. of samples to be selected (expandable)
      max_samples: {min: 2, max: 40, step: 1}

predictor:
    name: PolynomialRegressionPredictor
    # poly. degree (expandable)
    degree: [2, 3, 4, 5]
    
error_metrics:
    - name: MSE
    - name: MAE
    - name: R2
    - name: EVS

plot:
    - name: Boxplot
      path: plots
      title: Error Boxplot
      x: k_samples
      y: error_value
      n_plots:
        # list of columns that distinguish plots
        - selector
        - predictor
        - degree
        - error
